diesel::table! {
    github_link_statuses (url) {
        url -> Text,
        kind -> Text,
        host -> Text,
        owner -> Text,
        repo -> Text,
        resource_number -> BigInt,
        issue_state -> Nullable<Text>,
        pr_state -> Nullable<Text>,
        build_state -> Nullable<Text>,
        sonar_state -> Nullable<Text>,
        review_state -> Nullable<Text>,
        requested_reviewers -> Nullable<Text>,
        human_approval_count -> Nullable<BigInt>,
        human_approval_total -> Nullable<BigInt>,
        copilot_review_state -> Nullable<Text>,
        target_branch -> Nullable<Text>,
        merge_state -> Nullable<Text>,
        pr_is_draft -> Nullable<Bool>,
        unresolved_review_thread_count -> Nullable<BigInt>,
        fetched_at_epoch_seconds -> BigInt,
        refresh_after_epoch_seconds -> Nullable<BigInt>,
        last_error -> Nullable<Text>,
    }
}
